config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "static_pages#top"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :practice_parts, only: %i[index new create show edit update destroy]
  resources :practices, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  # "tasks#index"
  # resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header class="bg-white">
  <div class="container mx-auto flex items-center justify-between py-4">
    <div class="text-center">
      <%= link_to root_path, class: "block text-4xl font-bold text-gray-800 hover:text-gray-600" do %>
        English Pattern Practice
      <% end %>
      <%= link_to root_path, class: "block text-lg text-gray-800 hover:text-gray-600" do %>
        中学英語パターンプラクティス
      <% end %>
    </div>
    <div class="flex items-center space-x-4">
      <ul class="flex space-x-4 ml-auto container items-center">
        <li class="relative">
          <details>
            <summary>レッスン</summary>
              <ul class="bg-base-100 rounded-t-none p-2">
                <li><a><%= link_to "レッスン一覧", practices_path %></a></li>
                <li><a><%= link_to "ブックマーク一覧", bookmarks_practices_path %></a></li>
                <li><a><%= link_to "パターンプラクティスとは", "#" %></a></li>
          </details>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path, class: "bg-white text-black border border-black px-4 py-2 rounded" %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_registration_path, class: "bg-black text-white px-4 py-2 rounded block text-center" %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="bg-white py-4 shadow-md">
  <div class="container mx-auto flex justify-center space-x-8">
    <%= link_to "利用規約", "#", class: "text-gray-800 hover:text-gray-600" %>
    <%= link_to "プライバシーポリシー", "#", class: "text-gray-800 hover:text-gray-600" %>
    <%= link_to "お問い合わせ", "#", class: "text-gray-800 hover:text-gray-600" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-white">
  <div class="container mx-auto flex items-center justify-between py-4">
    <div class="text-center">
      <%= link_to root_path, class: "block text-4xl font-bold text-gray-800 hover:text-gray-600" do %>
        English Pattern Practice
      <% end %>
      <%= link_to root_path, class: "block text-lg text-gray-800 hover:text-gray-600" do %>
        中学英語パターンプラクティス
      <% end %>
    </div>
    <div class="flex items-center space-x-4">
      <ul class="flex space-x-4 ml-auto container items-center">
        <li class="relative">
          <details>
          <summary>レッスン</summary>
          <ul class="bg-base-100 rounded-t-none p-2">
            <li><a><%= link_to "レッスン一覧", practices_path %></a></li>
            <li><a><%= link_to "ブックマーク一覧", bookmarks_practices_path %></a></li>
            <li><a><%= link_to "パターンプラクティスとは", "#" %></a></li>
          </details>
        </li>
        <li>
          <%= link_to "設定", "#", class: "bg-white text-black border border-black px-4 py-2 rounded" %>
        </li>
        <li>
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "本当にサインアウトしますか？" }, class: "bg-black text-white px-4 py-2 rounded block text-center" %>
        </li>
      </ul>
    </div>
  </div>
</header>