config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "static_pages#top"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :practice_parts, only: %i[index new create show edit update destroy]
  resources :practices, only: %i[index new create show edit update destroy] do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  # "tasks#index"
  # resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/practice.rb
class Practice < ApplicationRecord
  validates :basic_english_sentence, presence: true
  validates :answer, presence: true

  belongs_to :practice_part
  has_many :bookmarks, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  def index
    @practices = Practice.includes(:practice_part)
    @current_practice = @practices[params[:practice_index].to_i]
    if params[:practice_index].to_i >= @practices.length
      redirect_to action: :index, practice_index: 0
    else
    @next_practice_index = params[:practice_index].to_i + 1
    end
  end

  def new
    @practice = Practice.new
  end

  def create
    @practice = Practice.new(practice_params)
    if @practice.save
      redirect_to practices_path, notice: "Practice was successfully created."
    else
      render :new
    end
  end

  def show
    @practice = Practice.find(params[:id])
    @practices = Practice.all
    current_index = @practices.index(@practice)
    @next_practice_index = params[:practice_index].to_i + 1
  end

  def edit
    @practice = Practice.find(params[:id])
  end

  def update
    @practice = Practice.find(params[:id])
    if @practice.update(practice_params)
      redirect_to practice_path(@practice), notice: "Question was successfully updated."
    else
      flash.now[:danger] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @practice.destroy
    redirect_to practices_path, notice: "Question was successfully destroyed."
  end

  def bookmarks
    @bookmark_practices = current_user.bookmark_practices.includes(:practice_part).order(created_at: :asc)
  end

  def practice_params
    params.require(:practice).permit(:basic_english_sentence, :basic_japanese_sentence, :question, :image, :difficulty_rating, answer)
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/_bookmark.html.erb
<%= link_to bookmarks_path(practice_id: practice.id), id: "bookmark-button-for-practice-#{practice.id}", data: { turbo_method: :post }, class: "text-yellow-500 hover:text-yellow-400" do %>
  <i class="fa-regular fa-star fa-lg text-yellow-500"></i>
<% end %>

app/views/practices/_bookmark_buttons.html.erb
<div class="ms-auto">
  <% if current_user.bookmark?(practice) %>
    <%= render "unbookmark", { practice: practice } %>
  <% else %>
    <%= render "bookmark", { practice: practice } %>
  <% end %>
</div>

app/views/practices/_practice.html.erb
    <tr>
      <th><%= practice.practice_part.number %></th>
      <td><%= practice.practice_part.title %></td>
      <td><%= practice.basic_english_sentence %></td>
      <td><%= practice.question %></td>
      <td><%= link_to "Play", practice_path(practice.id), method: :get, class: "btn" %></td>
      <td></td>
      <td><%= render "bookmark_buttons", { practice: practice } %></td>
    </tr>

app/views/practices/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(practice_id: practice.id)), id: "unbookmark-button-for-practice-#{practice.id}", data: { turbo_method: :delete }, class: "text-yellow-500 hover:text-yellow-400" do %>
  <i class="fa-solid fa-star fa-lg text-yellow"></i>
<% end %>

app/views/practices/bookmarks.html.erb
<div class="overflow-x-auto">
  <table class="table">
    <!-- head -->
    <thead>
    </thead>
    <tbody>
      <!-- row 1 -->
      <% if @bookmark_practices.present? %>
      <tr>
        <th></th>
        <th>Part</th>
        <th>基本文</th>
        <th>条件</th>
      </tr>
        <%= render @bookmark_practices %>
      <% else %>
        <p>No bookmarks</p>
      <% end %>
    </tbody>
  </table>
</div>

app/views/practices/index.html.erb
<div class="overflow-x-auto">
  <table class="table">
    <!-- head -->
    <thead>
      <tr>
        <th></th>
        <th>Part</th>
        <th>基本文</th>
        <th>条件</th>
      </tr>
    </thead>
    <tbody>
      <!-- row 1 -->
      <% @practices.each do |practice| %>
      <tr>
        <th><%= practice.practice_part.number %></th>
        <td><%= practice.practice_part.title %></td>
        <td><%= practice.basic_english_sentence %></td>
        <td><%= practice.question %></td>
        <td><%= link_to "Play", practice_path(practice.id), method: :get, class: "btn" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/practices/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>パターンプラクティス問題作成</h1>
      <%= form_with model: @practice, class: "new_practice" do |f| %>
        <div class="mb-3">
          <%= f.label :basic_english_sentence %>
          <%= f.text_field :basic_english_sentence, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :basic_japanese_sentence %>
          <%= f.text_field :basic_japanese_sentence, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :question %>
          <%= f.text_field :basic_english_sentence, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control", accept: 'image/*' %>
        </div>
        <div class="mb-3">
          <%= f.label :difficulty_rating %>
          <%= f.text_field :difficulty_rating, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :answer %>
          <%= f.text_field :answer, class: "form-control" %>
        </div>
        <%= f.submit nil, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/practices/show.html.erb
<div class="p-20px mt-12 text-center">
<tr>
<th>基本文</th>
<th><%= @practice.basic_english_sentence %></th>
</tr>
<tr>
<th></th>
<p class="text-center mb-12"><%= @practice.basic_japanese_sentence %></p>
</tr>
<tr>
<th>条件<p class="text-center text-2xl font-bold text-blue-500"><%= @practice.question %></p></th>
</tr>
<div class="w-7/12 h-2/12 block mr-auto ml-auto -z-10"><%= image_tag @practice.image_url, class: "w-full h-full object-contain" %></div>
<% if params[:answer] %>
  <p  class="text-center text-2xl font-bold text-rose-400 mb-4 -mt-8"><%= @practice.answer %></p>
<% end %>
<% if params[:answer] %>
  <p class="block mr-auto ml-auto"><%= link_to "Next", practice_path(Practice.find_by(id: @practice.id+1)), method: :get, class: "btn" %></p>
<% else %>
  <div class="flex space-x-4">
    <p class="block mr-auto ml-auto"><%= link_to "Answer", practice_path(@practice.id, answer: true), method: :get, class: "btn" %></p>
</div>
<% end %>
</div>